// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: pkg/proto/secretstorage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_CREDENTIALS RecordType = 0
	RecordType_TEXT_DATA   RecordType = 1
	RecordType_FILE        RecordType = 2
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "CREDENTIALS",
		1: "TEXT_DATA",
		2: "FILE",
	}
	RecordType_value = map[string]int32{
		"CREDENTIALS": 0,
		"TEXT_DATA":   1,
		"FILE":        2,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_secretstorage_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_pkg_proto_secretstorage_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{0}
}

// Authentication messages
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterResponse) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthenticateResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *AuthenticateResponse) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Record messages with oneof for content types
type Record struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Record_Credentials
	//	*Record_TextData
	//	*Record_FileData
	Content       isRecord_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetContent() isRecord_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Record) GetCredentials() *CredentialsData {
	if x != nil {
		if x, ok := x.Content.(*Record_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *Record) GetTextData() *TextData {
	if x != nil {
		if x, ok := x.Content.(*Record_TextData); ok {
			return x.TextData
		}
	}
	return nil
}

func (x *Record) GetFileData() *FileData {
	if x != nil {
		if x, ok := x.Content.(*Record_FileData); ok {
			return x.FileData
		}
	}
	return nil
}

type isRecord_Content interface {
	isRecord_Content()
}

type Record_Credentials struct {
	Credentials *CredentialsData `protobuf:"bytes,3,opt,name=credentials,proto3,oneof"`
}

type Record_TextData struct {
	TextData *TextData `protobuf:"bytes,4,opt,name=text_data,json=textData,proto3,oneof"`
}

type Record_FileData struct {
	FileData *FileData `protobuf:"bytes,5,opt,name=file_data,json=fileData,proto3,oneof"`
}

func (*Record_Credentials) isRecord_Content() {}

func (*Record_TextData) isRecord_Content() {}

func (*Record_FileData) isRecord_Content() {}

type CredentialsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsData) Reset() {
	*x = CredentialsData{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsData) ProtoMessage() {}

func (x *CredentialsData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsData.ProtoReflect.Descriptor instead.
func (*CredentialsData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{7}
}

func (x *CredentialsData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CredentialsData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TextData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextContent   string                 `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextData) Reset() {
	*x = TextData{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextData) ProtoMessage() {}

func (x *TextData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextData.ProtoReflect.Descriptor instead.
func (*TextData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{8}
}

func (x *TextData) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

type FileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{9}
}

type ServerRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          RecordType             `protobuf:"varint,3,opt,name=type,proto3,enum=secretstorage.RecordType" json:"type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRecord) Reset() {
	*x = ServerRecord{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRecord) ProtoMessage() {}

func (x *ServerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRecord.ProtoReflect.Descriptor instead.
func (*ServerRecord) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{10}
}

func (x *ServerRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerRecord) GetType() RecordType {
	if x != nil {
		return x.Type
	}
	return RecordType_CREDENTIALS
}

func (x *ServerRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ServerRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRecordRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *CreateRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type CreateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordResponse) Reset() {
	*x = CreateRecordResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResponse) ProtoMessage() {}

func (x *CreateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateRecordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRecordResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{13}
}

func (x *GetRecordRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *GetRecordRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Record        *Record                `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{14}
}

func (x *GetRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRecordRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *UpdateRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordResponse) Reset() {
	*x = UpdateRecordResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordResponse) ProtoMessage() {}

func (x *UpdateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRecordRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *DeleteRecordRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{19}
}

func (x *ListRecordsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Records       []*ServerRecord        `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{20}
}

func (x *ListRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListRecordsResponse) GetRecords() []*ServerRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetServerRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRecordsRequest) Reset() {
	*x = GetServerRecordsRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRecordsRequest) ProtoMessage() {}

func (x *GetServerRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetServerRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{21}
}

func (x *GetServerRecordsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type GetServerRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerRecords []*ServerRecord        `protobuf:"bytes,3,rep,name=server_records,json=serverRecords,proto3" json:"server_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRecordsResponse) Reset() {
	*x = GetServerRecordsResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRecordsResponse) ProtoMessage() {}

func (x *GetServerRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetServerRecordsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{22}
}

func (x *GetServerRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetServerRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetServerRecordsResponse) GetServerRecords() []*ServerRecord {
	if x != nil {
		return x.ServerRecords
	}
	return nil
}

// File streaming messages
type FileUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FileUploadRequest_Metadata
	//	*FileUploadRequest_Chunk
	Data          isFileUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{23}
}

func (x *FileUploadRequest) GetData() isFileUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileUploadRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*FileUploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *FileUploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*FileUploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isFileUploadRequest_Data interface {
	isFileUploadRequest_Data()
}

type FileUploadRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type FileUploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*FileUploadRequest_Metadata) isFileUploadRequest_Data() {}

func (*FileUploadRequest_Chunk) isFileUploadRequest_Data() {}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{24}
}

func (x *FileMetadata) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type FileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{25}
}

func (x *FileUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{26}
}

func (x *FileDownloadRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *FileDownloadRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type FileDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FileDownloadResponse_Info
	//	*FileDownloadResponse_Chunk
	Data          isFileDownloadResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadResponse) Reset() {
	*x = FileDownloadResponse{}
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadResponse) ProtoMessage() {}

func (x *FileDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_secretstorage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadResponse.ProtoReflect.Descriptor instead.
func (*FileDownloadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_secretstorage_proto_rawDescGZIP(), []int{27}
}

func (x *FileDownloadResponse) GetData() isFileDownloadResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileDownloadResponse) GetInfo() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*FileDownloadResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *FileDownloadResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*FileDownloadResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isFileDownloadResponse_Data interface {
	isFileDownloadResponse_Data()
}

type FileDownloadResponse_Info struct {
	Info *FileMetadata `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type FileDownloadResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*FileDownloadResponse_Info) isFileDownloadResponse_Data() {}

func (*FileDownloadResponse_Chunk) isFileDownloadResponse_Data() {}

var File_pkg_proto_secretstorage_proto protoreflect.FileDescriptor

const file_pkg_proto_secretstorage_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/secretstorage.proto\x12\rsecretstorage\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"y\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\tR\x04salt\"M\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"}\n" +
	"\x14AuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\tR\x04salt\".\n" +
	"\rLogoutRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"D\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf8\x01\n" +
	"\x06Record\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12B\n" +
	"\vcredentials\x18\x03 \x01(\v2\x1e.secretstorage.CredentialsDataH\x00R\vcredentials\x126\n" +
	"\ttext_data\x18\x04 \x01(\v2\x17.secretstorage.TextDataH\x00R\btextData\x126\n" +
	"\tfile_data\x18\x05 \x01(\v2\x17.secretstorage.FileDataH\x00R\bfileDataB\t\n" +
	"\acontent\"I\n" +
	"\x0fCredentialsData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"-\n" +
	"\bTextData\x12!\n" +
	"\ftext_content\x18\x01 \x01(\tR\vtextContent\"\n" +
	"\n" +
	"\bFileData\"\x9f\x01\n" +
	"\fServerRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.secretstorage.RecordTypeR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"c\n" +
	"\x13CreateRecordRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.secretstorage.RecordR\x06record\"g\n" +
	"\x14CreateRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"N\n" +
	"\x10GetRecordRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"v\n" +
	"\x11GetRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x06record\x18\x03 \x01(\v2\x15.secretstorage.RecordR\x06record\"c\n" +
	"\x13UpdateRecordRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.secretstorage.RecordR\x06record\"J\n" +
	"\x14UpdateRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Q\n" +
	"\x13DeleteRecordRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"J\n" +
	"\x14DeleteRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x12ListRecordsRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"\x80\x01\n" +
	"\x13ListRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\arecords\x18\x03 \x03(\v2\x1b.secretstorage.ServerRecordR\arecords\"8\n" +
	"\x17GetServerRecordsRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"\x92\x01\n" +
	"\x18GetServerRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x0eserver_records\x18\x03 \x03(\v2\x1b.secretstorage.ServerRecordR\rserverRecords\"n\n" +
	"\x11FileUploadRequest\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.secretstorage.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x87\x01\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"H\n" +
	"\x12FileUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Q\n" +
	"\x13FileDownloadRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\"i\n" +
	"\x14FileDownloadResponse\x121\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.secretstorage.FileMetadataH\x00R\x04info\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data*6\n" +
	"\n" +
	"RecordType\x12\x0f\n" +
	"\vCREDENTIALS\x10\x00\x12\r\n" +
	"\tTEXT_DATA\x10\x01\x12\b\n" +
	"\x04FILE\x10\x022\xfa\x01\n" +
	"\vAuthService\x12K\n" +
	"\bRegister\x12\x1e.secretstorage.RegisterRequest\x1a\x1f.secretstorage.RegisterResponse\x12W\n" +
	"\fAuthenticate\x12\".secretstorage.AuthenticateRequest\x1a#.secretstorage.AuthenticateResponse\x12E\n" +
	"\x06Logout\x12\x1c.secretstorage.LogoutRequest\x1a\x1d.secretstorage.LogoutResponse2\xf0\x04\n" +
	"\rRecordService\x12W\n" +
	"\fCreateRecord\x12\".secretstorage.CreateRecordRequest\x1a#.secretstorage.CreateRecordResponse\x12N\n" +
	"\tGetRecord\x12\x1f.secretstorage.GetRecordRequest\x1a .secretstorage.GetRecordResponse\x12W\n" +
	"\fUpdateRecord\x12\".secretstorage.UpdateRecordRequest\x1a#.secretstorage.UpdateRecordResponse\x12W\n" +
	"\fDeleteRecord\x12\".secretstorage.DeleteRecordRequest\x1a#.secretstorage.DeleteRecordResponse\x12T\n" +
	"\vListRecords\x12!.secretstorage.ListRecordsRequest\x1a\".secretstorage.ListRecordsResponse\x12S\n" +
	"\n" +
	"UploadFile\x12 .secretstorage.FileUploadRequest\x1a!.secretstorage.FileUploadResponse(\x01\x12Y\n" +
	"\fDownloadFile\x12\".secretstorage.FileDownloadRequest\x1a#.secretstorage.FileDownloadResponse0\x01B6Z4github.com/DanilNaum/secret-storage-client/pkg/protob\x06proto3"

var (
	file_pkg_proto_secretstorage_proto_rawDescOnce sync.Once
	file_pkg_proto_secretstorage_proto_rawDescData []byte
)

func file_pkg_proto_secretstorage_proto_rawDescGZIP() []byte {
	file_pkg_proto_secretstorage_proto_rawDescOnce.Do(func() {
		file_pkg_proto_secretstorage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_secretstorage_proto_rawDesc), len(file_pkg_proto_secretstorage_proto_rawDesc)))
	})
	return file_pkg_proto_secretstorage_proto_rawDescData
}

var file_pkg_proto_secretstorage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_secretstorage_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_pkg_proto_secretstorage_proto_goTypes = []any{
	(RecordType)(0),                  // 0: secretstorage.RecordType
	(*RegisterRequest)(nil),          // 1: secretstorage.RegisterRequest
	(*RegisterResponse)(nil),         // 2: secretstorage.RegisterResponse
	(*AuthenticateRequest)(nil),      // 3: secretstorage.AuthenticateRequest
	(*AuthenticateResponse)(nil),     // 4: secretstorage.AuthenticateResponse
	(*LogoutRequest)(nil),            // 5: secretstorage.LogoutRequest
	(*LogoutResponse)(nil),           // 6: secretstorage.LogoutResponse
	(*Record)(nil),                   // 7: secretstorage.Record
	(*CredentialsData)(nil),          // 8: secretstorage.CredentialsData
	(*TextData)(nil),                 // 9: secretstorage.TextData
	(*FileData)(nil),                 // 10: secretstorage.FileData
	(*ServerRecord)(nil),             // 11: secretstorage.ServerRecord
	(*CreateRecordRequest)(nil),      // 12: secretstorage.CreateRecordRequest
	(*CreateRecordResponse)(nil),     // 13: secretstorage.CreateRecordResponse
	(*GetRecordRequest)(nil),         // 14: secretstorage.GetRecordRequest
	(*GetRecordResponse)(nil),        // 15: secretstorage.GetRecordResponse
	(*UpdateRecordRequest)(nil),      // 16: secretstorage.UpdateRecordRequest
	(*UpdateRecordResponse)(nil),     // 17: secretstorage.UpdateRecordResponse
	(*DeleteRecordRequest)(nil),      // 18: secretstorage.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),     // 19: secretstorage.DeleteRecordResponse
	(*ListRecordsRequest)(nil),       // 20: secretstorage.ListRecordsRequest
	(*ListRecordsResponse)(nil),      // 21: secretstorage.ListRecordsResponse
	(*GetServerRecordsRequest)(nil),  // 22: secretstorage.GetServerRecordsRequest
	(*GetServerRecordsResponse)(nil), // 23: secretstorage.GetServerRecordsResponse
	(*FileUploadRequest)(nil),        // 24: secretstorage.FileUploadRequest
	(*FileMetadata)(nil),             // 25: secretstorage.FileMetadata
	(*FileUploadResponse)(nil),       // 26: secretstorage.FileUploadResponse
	(*FileDownloadRequest)(nil),      // 27: secretstorage.FileDownloadRequest
	(*FileDownloadResponse)(nil),     // 28: secretstorage.FileDownloadResponse
}
var file_pkg_proto_secretstorage_proto_depIdxs = []int32{
	8,  // 0: secretstorage.Record.credentials:type_name -> secretstorage.CredentialsData
	9,  // 1: secretstorage.Record.text_data:type_name -> secretstorage.TextData
	10, // 2: secretstorage.Record.file_data:type_name -> secretstorage.FileData
	0,  // 3: secretstorage.ServerRecord.type:type_name -> secretstorage.RecordType
	7,  // 4: secretstorage.CreateRecordRequest.record:type_name -> secretstorage.Record
	7,  // 5: secretstorage.GetRecordResponse.record:type_name -> secretstorage.Record
	7,  // 6: secretstorage.UpdateRecordRequest.record:type_name -> secretstorage.Record
	11, // 7: secretstorage.ListRecordsResponse.records:type_name -> secretstorage.ServerRecord
	11, // 8: secretstorage.GetServerRecordsResponse.server_records:type_name -> secretstorage.ServerRecord
	25, // 9: secretstorage.FileUploadRequest.metadata:type_name -> secretstorage.FileMetadata
	25, // 10: secretstorage.FileDownloadResponse.info:type_name -> secretstorage.FileMetadata
	1,  // 11: secretstorage.AuthService.Register:input_type -> secretstorage.RegisterRequest
	3,  // 12: secretstorage.AuthService.Authenticate:input_type -> secretstorage.AuthenticateRequest
	5,  // 13: secretstorage.AuthService.Logout:input_type -> secretstorage.LogoutRequest
	12, // 14: secretstorage.RecordService.CreateRecord:input_type -> secretstorage.CreateRecordRequest
	14, // 15: secretstorage.RecordService.GetRecord:input_type -> secretstorage.GetRecordRequest
	16, // 16: secretstorage.RecordService.UpdateRecord:input_type -> secretstorage.UpdateRecordRequest
	18, // 17: secretstorage.RecordService.DeleteRecord:input_type -> secretstorage.DeleteRecordRequest
	20, // 18: secretstorage.RecordService.ListRecords:input_type -> secretstorage.ListRecordsRequest
	24, // 19: secretstorage.RecordService.UploadFile:input_type -> secretstorage.FileUploadRequest
	27, // 20: secretstorage.RecordService.DownloadFile:input_type -> secretstorage.FileDownloadRequest
	2,  // 21: secretstorage.AuthService.Register:output_type -> secretstorage.RegisterResponse
	4,  // 22: secretstorage.AuthService.Authenticate:output_type -> secretstorage.AuthenticateResponse
	6,  // 23: secretstorage.AuthService.Logout:output_type -> secretstorage.LogoutResponse
	13, // 24: secretstorage.RecordService.CreateRecord:output_type -> secretstorage.CreateRecordResponse
	15, // 25: secretstorage.RecordService.GetRecord:output_type -> secretstorage.GetRecordResponse
	17, // 26: secretstorage.RecordService.UpdateRecord:output_type -> secretstorage.UpdateRecordResponse
	19, // 27: secretstorage.RecordService.DeleteRecord:output_type -> secretstorage.DeleteRecordResponse
	21, // 28: secretstorage.RecordService.ListRecords:output_type -> secretstorage.ListRecordsResponse
	26, // 29: secretstorage.RecordService.UploadFile:output_type -> secretstorage.FileUploadResponse
	28, // 30: secretstorage.RecordService.DownloadFile:output_type -> secretstorage.FileDownloadResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_proto_secretstorage_proto_init() }
func file_pkg_proto_secretstorage_proto_init() {
	if File_pkg_proto_secretstorage_proto != nil {
		return
	}
	file_pkg_proto_secretstorage_proto_msgTypes[6].OneofWrappers = []any{
		(*Record_Credentials)(nil),
		(*Record_TextData)(nil),
		(*Record_FileData)(nil),
	}
	file_pkg_proto_secretstorage_proto_msgTypes[23].OneofWrappers = []any{
		(*FileUploadRequest_Metadata)(nil),
		(*FileUploadRequest_Chunk)(nil),
	}
	file_pkg_proto_secretstorage_proto_msgTypes[27].OneofWrappers = []any{
		(*FileDownloadResponse_Info)(nil),
		(*FileDownloadResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_secretstorage_proto_rawDesc), len(file_pkg_proto_secretstorage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_secretstorage_proto_goTypes,
		DependencyIndexes: file_pkg_proto_secretstorage_proto_depIdxs,
		EnumInfos:         file_pkg_proto_secretstorage_proto_enumTypes,
		MessageInfos:      file_pkg_proto_secretstorage_proto_msgTypes,
	}.Build()
	File_pkg_proto_secretstorage_proto = out.File
	file_pkg_proto_secretstorage_proto_goTypes = nil
	file_pkg_proto_secretstorage_proto_depIdxs = nil
}
